// Tailwind class sets for the few non-MUI components. Colours come from the
// Garnet tokens in tailwind.config.js (neutral / ink / primary).
export const themeClasses = {
  light: {
    bg: 'bg-neutral-50',
    reverseBg: 'bg-neutral-900',
    reverseText: 'text-neutral-0',
    bgAuth: 'bg-neutral-50',
    text: 'text-neutral-900',
    textMuted: 'text-neutral-600',
    border: 'border-neutral-300',
    input: 'border-neutral-300 bg-neutral-0 text-neutral-900',
    inputBg: 'bg-neutral-0',
    icon: 'text-neutral-500',
    focusBorder: 'border-primary-600',
    dropdownBg: 'bg-neutral-0',
    dropdownItemHover: 'hover:bg-neutral-100',
    dropdownItemSelected: 'bg-primary-50',
    hover: 'hover:bg-neutral-900 hover:text-neutral-0',
    hoverReverse: 'hover:bg-neutral-0 hover:text-neutral-900',
    navBg: 'bg-neutral-0',
  },
  dark: {
    bg: 'bg-ink-base',
    reverseBg: 'bg-ink-text',
    reverseText: 'text-ink-base',
    bgAuth: 'bg-ink-base',
    text: 'text-ink-text',
    textMuted: 'text-ink-muted',
    border: 'border-ink-strong',
    input: 'border-ink-strong bg-ink-raised text-ink-text',
    inputBg: 'bg-ink-raised',
    icon: 'text-ink-muted',
    focusBorder: 'border-primary-400',
    dropdownBg: 'bg-ink-paper',
    dropdownItemHover: 'hover:bg-ink-raised',
    dropdownItemSelected: 'bg-primary-900',
    hover: 'hover:bg-ink-text hover:text-ink-base',
    hoverReverse: 'hover:bg-ink-base hover:text-ink-text',
    navBg: 'bg-ink-paper',
  },
};
